<!doctype html>
<html lang="en">
<head>
    <title>배송지 변경</title>
    <style type="text/css">
        body {
            color: #4A4A4A;
        }
        .select_addr_list {
            width: 100%;
            height: 100%;
        }

        .select_addr_list ul {
            padding: 0px;
        }

        .select_addr_list ul li {
            list-style: none;
            border: 2px solid #CCCCCC;
            width: 100%;
            height: 100px;
            padding: 10px;
            border-collapse: collapse;
            box-sizing: border-box;
            margin-bottom: 5px;
            cursor: pointer;
        }
        .select_addr_list ul li:hover {
            border: 2px solid #7167AB;
        }
        .select_addr_list ul li div {
            line-height: 25px;
        }

        .none {
            text-align: center;
            list-style: none;
            border: 2px solid #7167AB;
            width: 100%;
            height: 100px;
            padding: 10px;
            border-collapse: collapse;
            box-sizing: border-box;
            margin-bottom: 5px;
        }
        .select_addr_list .name {
            font-weight: bold;
        }
    </style>
</head>

<body>
<div class="select_addr_list">
    <?php if (!empty($address_list)) { ?>
        <ul>
            <?php foreach ($address_list as $key => $value) { ?>
                <li data-address_idx="<?= $value['address_idx'] ?>">
                    <div class="name"><?= $value['name'] ?></div>
                    <div class="addr"><?= !empty($value['zipcode']) ? '(' . $value['zipcode'] . ')' : '' ?> <?= $value['addr1st'] ?> <?= $value['addr2nd'] ?></div>
                    <div class="phone"><?= $value['telphone'] ?></div>
                </li>
            <?php } ?>
        </ul>
    <?php } else { ?>
        <div class="none">등록된 주소가 없습니다.</div>
    <?php } ?>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script type="text/javascript">
    var addressData = <?php echo !empty($address_list_json) ? $address_list_json : '{}' ?>;
    $(document).ready(function () {
        $('ul li').on('click', function () {
            console.log(addressData.length);
            if (addressData.length == 0) {
                return false;
            }

            var selectedAddr = addressData[$(this).data('address_idx')] || {};
            if (selectedAddr.length == 0) {
                alert("선택한 주소지가 정상적이지 않습니다.");
                return false;
            }

            $('#orderForm input[name="buyer_phone"]', opener.document).val(selectedAddr.telphone || '');
            $('#orderForm input[name="buyer_name"]', opener.document).val(selectedAddr.name || '');
            $('#orderForm input[name="address_idx"]', opener.document).val(selectedAddr.address_idx || '');
            $('#orderForm input[name="zipcode"]', opener.document).val(selectedAddr.zipcode || '');
            $('#orderForm input[name="addr1st"]', opener.document).val(selectedAddr.addr1st || '');
            $('#orderForm input[name="addr2nd"]', opener.document).val(selectedAddr.addr2nd || '');
            self.close();
        });

    });
</script>
</body>
</html>