<style type="text/css">
    .container {
        width: 1200px;
        min-width: 960px;
        margin: auto;
        text-align: center;
        padding: 70px 0;
        height: 100%;
    }

    .container a:link, .container a:visited, .container a:hover, .container a:active {
        color: #545454;
    }
    .find_form * {
        box-sizing: border-box;
        overflow: hidden;
    }

    div.find_form {
        position: relative;
        text-align: center;
        padding-bottom: 70px;
        margin-bottom: 140px;
    }
    .find_form .inner {
        border: 1px solid #cccccc;
        border-radius: 8px;
        padding: 51px;
        width: 500px;
        display: inline-block;
        margin: 50px 0;
    }

    .inner .form_inner {
        padding: 20px;
    }

    .form_inner p{
        font-size: 15px;
        text-align: left;
    }

    .inner .confirm {
        text-align: center;
        border-top: solid 1px #CBCBCB;
        margin-top: 20px;
    }

    input[type=text], input[type=password] {
        margin-bottom: 7px;
        box-sizing: border-box;
        height: 47px;
    }

    .btn.btn-primary {
        width: 75px;
        height: 40px;
        border-radius: 7px;
        background-color: #452b78;
        color: #ffffff;
        border: none;
        margin-top: 21px;
    }

    .find_form div span:first-child {
        float: left;
        font-weight: bold;
    }

    .find_form div span:nth-child(2) {
        float: right;
        font-weight: bold;
        color: #452b78;
    }

    .form-control {
        display: block;
        width: 100%;
        padding: .375rem .75rem;
        font-size: 1rem;
        line-height: 1.5;
        color: #495057;
        background-color: #fff;
        background-clip: padding-box;
        border: 1px solid #ced4da;
        border-radius: .25rem;
        transition: border-color .15s ease-in-out, box-shadow .15s ease-in-out;
    }
</style>
<div class="container">
    <div class="find_form contents">
        <div class="title">비밀번호찾기</div>
        <hr class="title-line">
        <div class="inner">
            <form action="/member/findPassword" method="post" id="findPasswordForm">
                <div class="form_inner">
                    <input type="text" class="form-control" name="name" placeholder="이름을 입력해주세요." value="">
                    <input type="text" class="form-control" name="email" placeholder="이메일을 입력해주세요." value="">
                    <p>
                        비밀번호를 잊으셨나요? 이메일을 입력해주세요.<br>
                        이메일로 인증번호를 보내드립니다.<br>
                        도착하지 않은 경우 스팸함을 확인해주세요.<br>
                    </p>
                </div>
                <div class="confirm">
                    <input type="button" class="btn btn-primary submit" value="확인">
                </div>
            </form>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        $('.submit').on('click', function () {
            if (!$('input[name="name"]').val()) {
                alert('이름을 입력해주세요.');
                return false;
            }

            if (!checkEmail($('input[name="email"]'))) {
                return false;
            }
            $('#findPasswordForm').submit();
        });

        var checkEmail = function (email) {
            var re = /^([\w-]+(?:\.[\w-]+)*)@((?:[\w-]+\.)*\w[\w-]{0,66})\.([a-z]{2,6}(?:\.[a-z]{2})?)$/i;
            if (email.val().length == 0) {
                alert('이메일을 입력해주세요.');
                email.focus();
                return false;
            }
            if (email.val().length > 0 && !re.test(email.val())) {
                alert('이메일이 유효하지 않습니다.');
                email.focus();
                return false;
            }
            return true;
        }
    });
</script>