<style type="text/css">
    .container {
        width: 1200px;
        min-width: 960px;
        margin: auto;
        text-align: center;
        padding: 70px 0;
        height: 100%;
    }

    .container a:link, .container a:visited, .container a:hover, .container a:active {
        color: #545454;
    }

    .login_form * {
        box-sizing: border-box;
        overflow: hidden;
    }

    div.login_form {
        position: relative;
        text-align: center;
        padding-bottom: 70px;
        margin-bottom: 140px;
    }

    .login_form .inner {
        border: 1px solid #cccccc;
        border-radius: 8px;
        padding: 50px 52px;
        width: 500px;
        display: inline-block;
        margin: 50px 0;
        color: #545454;
        font-size: 14px;
    }

    input[type=text], input[type=password] {
        margin-bottom: 7px;
        box-sizing: border-box;
        height: 47px;
    }

    .btn.btn-primary {
        width: 100%;
        height: 55px;
        background-color: #452b78;
        color: #ffffff;
        border: none;
        margin-top: 21px;
    }

    .login_form div span:first-child {
        float: left;
        font-weight: bold;
    }

    .login_form div span:nth-child(2) {
        float: right;
        font-weight: bold;
        color: #452b78;
    }

    .login_form #find_passwd {
        cursor: pointer;
    }

    .login_form .sns_group {
        left: 6px;
        top: 10px;
    }

    .login_form .sns_group img {
        margin-right: 7px;
    }

    .sns_group img {
        cursor: pointer;
    }
</style>
<div class="container">
    <div class="login_form contents">
        <div class="title">비밀번호 변경</div>
        <hr class="title-line">
        <div>
            <div class="inner">
                <form name="changePassword" action="/member/changePassword/" method="post">
                    <input type="hidden" name="name" id="name" value="<?= $name ?>">
                    <input type="hidden" name="email" id="email" value="<?= $email ?>">
                    <div id="auth_form">
                        <input type="text" class="form-control" name="find_pwd_auth_number" id="find_pwd_auth_number" placeholder="인증번호를 입력해주세요." value="">
                        <input type="button" class="btn btn-primary button" id="auth_btn" value="인증">
                    </div>
                    <div id="pswd_form" style="display: none;">
                        <input type="password" class="form-control" name="password" placeholder="새 비밀번호를 입력해주세요" value="">
                        <input type="password" class="form-control" name="confirm_password"
                               placeholder="새 비밀번호(확인)를 입력해주세요"
                               value="">
                        <input type="submit" class="btn btn-primary submit" value="변경">
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function () {
        $('#auth_btn').on('click',function () {
            $.ajax({
                url: '/Member/confirmAuthNumber',
                type: "POST",
                data: {
                    auth: encodeURI($('#find_pwd_auth_number').val()),
                    name : encodeURI($('#name').val()),
                    email : encodeURI($('#email').val())
                },
                async: true,
                dataType: 'json',
                complete: function (result) {
                    var data = result.responseJSON;
                    if (data === 'success') {
                        $('#auth_form').hide();
                        $('#pswd_form').show();
                    } else {
                        alert('인증에 실패하였습니다.');
                    }
                }
            })
        });

        $(".btn.submit").click(function () {
            var password = $("input[name=password]");
            var confirm_password = $("input[name=confirm_password]");

            if (password.val() == "") {
                alert("비밀번호를 입력해주세요.");
                password.focus();
                return false;
            }

            if (confirm_password.val() == "") {
                alert("비밀번호(확인)를 입력해주세요.");
                confirm_password.focus();
                return false;
            }

            if (!checkPasswd(password.val())) {
                return false;
            }

            if (password.val() != confirm_password.val()) {
                alert("비밀번호가 같지 않습니다.");
                return false;
            }


            if (!checkPasswd(confirm_password.val())) {
                return false;
            }

            $("form").submit();
        });


        var checkPasswd = function (password) {
            if (password.length < 8) {
                alert("비밀번호는 영문(대소문자구분),숫자,특수문자(~!@#$%^&*()-_? 만 허용)를 혼용하여 8~16자를 입력해주세요.");
                return false;
            }
            if (!password.match(/([a-zA-Z0-9].*[!,@,#,$,%,^,&,*,?,_,~,-])|([!,@,#,$,%,^,&,*,?,_,~,-].*[a-zA-Z0-9])/)) {
                alert("비밀번호는 영문(대소문자구분),숫자,특수문자(~!@#$%^&*()-_? 만 허용)를 혼용하여 8~16자를 입력해주세요.");
                return false;
            }
            return true;
        }
    });
</script>