<script>
    window.fbAsyncInit = function () {
        FB.init({
            appId: '' ,//'892784224261148',
            cookie: true,
            xfbml: true,
            version: 'v2.8'
        });

        FB.AppEvents.logPageView();
    };

    (function (d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) {
            return;
        }
        js = d.createElement(s);
        js.id = id;
        js.src = "https://connect.facebook.net/en_US/sdk.js";
        fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));

    function checkLoginState() {
        FB.getLoginStatus(function (response) {
            statusChangeCallback(response);
        });
    }

    function statusChangeCallback(response) {
        console.log(response);
    }
</script>

<div class="sns_group">
    <div class="sns_login" data-sns="kakao"><img src="/img/member/kakao_login.png"></div>
     <div class="sns_login" data-sns="facebook"><img src="/img/member/facebook_login.png"></div>
    <div class="fb-like" data-share="true" data-width="450" data-show-faces="true"></div>
    <div class="sns_login" data-sns="naver"><img src="/img/member/naver_login.png"></div>
</div>

